canonical: https://www.ehealth.fgov.be/standards/fhir
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: ehealth.fgov.standards.fhir
name: EhealthFgovStandardsFhir
status: active
version: 1.3.3-beta
